<?php $this->loadView("index" . DS . "topo"); ?>

    <div class="row-fluid">

        <?php
            if (CRUD\Session::get("cadastro")): ?>

                <div class="alert <?= CRUD\Session::get("cadastro-class"); ?>">
                    <?= CRUD\Session::get("cadastro-msg"); ?>
                </div><?php
                CRUD\Session::delete("cadastro");
                CRUD\Session::delete("cadastro-class");
                CRUD\Session::delete("cadastro-msg");

            endif;
        ?>

        <form class="form-horizontal" method="post" action="<?= $urlAction; ?>">
            <fieldset>

                <legend><?= $pageDesc; ?></legend>

                <div class="control-group">
                    <label for="input-nome" class="control-label">Nome</label>
                    <div class="controls">
                        <input type="text" required value="<?= (isset($cliente["nome"])) ? $cliente["nome"] : ""; ?>"
                               name="input-nome" class="input-xlarge focused">
                    </div>
                </div>

                <div class="control-group">
                    <label for="input-telefone" class="control-label">Telefone</label>
                    <div class="controls">
                        <input type="tel" required
                               value="<?= (isset($cliente["telefone"])) ? $cliente["telefone"] : ""; ?>"
                               name="input-telefone" class="input-xlarge">
                    </div>
                </div>

                <div class="control-group">
                    <label for="input-email" class="control-label">E-mail</label>
                    <div class="controls">
                        <input type="email" required value="<?= (isset($cliente["email"])) ? $cliente["email"] : ""; ?>"
                               name="input-email" class="input-xlarge">
                    </div>
                </div>

                <div class="form-actions">
                    <button class="btn btn-primary" type="submit"><?= $submitDesc; ?></button>
                </div>

            </fieldset>
        </form>


    </div>

<?php $this->loadView("index" . DS . "rodape"); ?>