<?php $this->loadView("index" . DS . "topo"); ?>

    <div class="row-fluid">
        <?php
        $remove_ok = CRUD\Session::get("remove-ok");
        if (!empty($remove_ok)): ?>
            <div class="alert alert-success">Cliente excluído com sucesso!</div> <?php
            CRUD\Session::delete("remove-ok");
        endif;
        ?>

        <div>
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>E-mail</th>
                    <th class="operacoes">Atualizar</th>
                    <th class="operacoes">Remover</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($clientes)) : ?>
                    <?php foreach ($clientes as $cliente) : ?>
                        <tr>
                            <td><?= $cliente['nome']; ?></td>
                            <td><?= $cliente['telefone']; ?></td>
                            <td><?= $cliente['email']; ?></td>
                            <td class="center">
                                <a class="c-atualizar" href="<?= SITE_URL; ?>/cliente/exibir/<?= $cliente['id']; ?>"
                                   title="Atualizar dados"><img src="<?= IMG_URL; ?>/update.png"></a>
                            </td>
                            <td class="center">
                                <a class="c-remover" href="<?= SITE_URL; ?>/cliente/remover/<?= $cliente['id']; ?>"
                                   title="Remover"><img src="<?= IMG_URL; ?>/delete.png"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr>
                        <td colspan="5" class="center"><i>Nenhum registro encontrado.</i></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>

<?php $this->loadView("index" . DS . "rodape"); ?>